title: Finance with Yash
description: Enthusiastic equity research and financial analysis platform focused on understanding businesses, valuations, and financial markets.
author: Yash

theme: jekyll-theme-cayman

